### ISSUE TITLE
setting global.affinity leads to wrong set of tolerations

### ISSUE THREAD

**Issue by akalitenya** [stafftastic/jitsu-chart#41]
https://github.com/stafftastic/jitsu-chart/blob/952676061f6ff20d6a7296276558667f90462e79/templates/migration/job.yaml#L87
https://github.com/stafftastic/jitsu-chart/blob/952676061f6ff20d6a7296276558667f90462e79/templates/event-log-trim/cronjob.yaml#L108
https://github.com/stafftastic/jitsu-chart/blob/952676061f6ff20d6a7296276558667f90462e79/templates/bulker/deployment.yaml#L139
https://github.com/stafftastic/jitsu-chart/blob/952676061f6ff20d6a7296276558667f90462e79/templates/event-log-init/job.yaml#L105

it results to install error: "Error: INSTALLATION FAILED: Deployment in version "v1" cannot be handled as a Deployment: json: cannot unmarshal object into Go struct field PodSpec.spec.template.spec.tolerations of type []v1.Toleration"

**Comment by echozio** [comment]
Good catch, thanks!

Fixed in [v1.8.6](https://github.com/stafftastic/jitsu-chart/releases/tag/v1.8.6)
